Revert r33023
Was causing compile troubles with MSVC:
wm_operators.c
C:\Program Files\Microsoft Visual Studio 9.0\VC\INCLUDE\io.h(322) : error C3163: '_write': attribute
s inconsistent with previous declaration
        C:\Program Files\Microsoft Visual Studio 9.0\VC\INCLUDE\io.h(224) : see declaration of '_wri
te'
scons: *** [C:\blenderdev\b250\buildvc\source\blender\windowmanager\intern\wm_operators.obj] Error 2